### ISSUE TITLE
YAML colon handling incompatible with cloud-init's pyyaml

### ISSUE THREAD

**Issue by gucharbon** [canonical/multipass#1097]
### Context

- I'm running `multipass 0.8.0+win` on Windows 10 (17763).
- I'm trying to install Docker using cloud-init. 
- I'm using multipass to start a virtual machine using the following command:

`multipass launch -n swarm --cpus 2 --mem 4G --cloud-init cloud-config.yaml`

> Note: I didn't know how to name this issue, feel free to rename it

### Issue

`cloud-init` fails to load YAML with the following error:

```
2019-09-27 14:59:06,516 - util.py[WARNING]: Failed loading yaml blob. Invalid format at line 19 column 16: "while scanni
ng a plain scalar
  in "<unicode string>", line 19, column 16:
        -   [echo, Installing docker using script f ...
                   ^
found unexpected ':'
  in "<unicode string>", line 19, column 57:
     ... g docker using script from https://get.docker.com]
                                         ^
Please check http://pyyaml.org/wiki/YAMLColonInFlowContext for details."
2019-09-27 14:59:06,550 - util.py[WARNING]: Failed loading yaml blob. Invalid format at line 19 column 16: "while scanni
ng a plain scalar
  in "<unicode string>", line 19, column 16:
        -   [echo, Installing docker using script f ...
                   ^
found unexpected ':'
  in "<unicode string>", line 19, column 57:
     ... g docker using script from https://get.docker.com]
                                         ^
```

### Given cloud-config

```yaml
#cloud-config

groups:
  - docker

users:
  - name: gcharbon
    gecos: Guillaume Charbonnier
    primary_group: gcharbon
    groups: docker
    home: /home/gcharbon
    shell: /bin/bash
    lock_passwd: true
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ssh-rsa <ssh_key>

package_upgrade: true

rumcmd:
  - [ mkdir, /run/install_docker ]
  - [ echo, "Installing docker using script from https://get.docker.com" ]
  - [ curl, -fsSL, "https://get.docker.com", -o, /run/install_docker/get-docker.sh ]
  - [ sh, /run/install_docker/get-docker.sh ]
  - [ docker, swarm, init ]

final_message: >
   The system is finally up, after $UPTIME seconds.
   Docker has been installed and packages are up to date
```

### Additional information

The command `sudo cat /var/lib/cloud/instances/swarm/user-data.txt` returns the following:

```yaml
#cloud-config
groups:
    -   docker
users:
    -   name: gcharbon
        gecos: Guillaume Charbonnier
        primary_group: gcharbon
        groups: docker
        home: /home/gcharbon
        shell: /bin/bash
        lock_passwd: true
        sudo: ALL=(ALL) NOPASSWD:ALL
        ssh_authorized_keys:
            -   ssh-rsa <ssh_key>
    -   default
package_upgrade: true
rumcmd:
    -   [mkdir, /run/install_docker]
    -   [echo, Installing docker using script from https://get.docker.com]
    -   [curl, -fsSL, https://get.docker.com, -o, /run/install_docker/get-docker.sh]
    -   [sh, /run/install_docker/get-docker.sh]
    -   [docker, swarm, init]
final_message: "The system is finally up, after $UPTIME seconds. Docker has been installed and packages are up to date\n
"
```

As you can see, quotes around commands in `runcmd` block disappeared.

Why does `multipass` removes the quotes around URLs ? 
Am I not using the correct format expected by `cloud-init` or is it a problem related to `multipass`? 

I tried to follow [this example](https://github.com/number5/cloud-init/blob/master/doc/examples/cloud-config.txt#L125) when writing my cloud-config file, that's why I'm confident that cloud-config syntax is correct.

> Note: BTW, is it expected behaviour that default user is added even if it was not specified in my `cloud-config.yml`? 

### Picture of a cute animal

I hope you will be happy to have taken a look to this issue once you will see my bunny sleeping with my cat 🐰 🐱 
![image](https://user-images.githubusercontent.com/36370689/65777178-cffc7d00-e143-11e9-9206-eb9a685d9c52.png)

Thanks in advance and thank you for the awesome tool that is ` multipass` :)
