### ISSUE TITLE
multipass ignores cloud init configuration

### ISSUE THREAD

**Issue by Samet-MohamedAmin** [canonical/multipass#1404]
I'm using multipass with hyper-v driver on windows.
I have created VM with multipass with the cloud-init configuration:
`multipass launch --name mpass-14 --cpus 2 --mem 2G --disk 20G --cloud-init .\custom-netwosrking.cfg`  

``` yaml
network:
  ethernets:
    eth0:
      addresses:
      - 172.16.110.<xxx>/24
      gateway4: 172.16.110.1
      nameservers:
        addresses:
        - 127.0.0.53
  version: 2
```

The problem is that the ip of the newely create VM does not change.  
I have tried other configuration from
[cloudinit.readthecos.io](https://cloudinit.readthedocs.io/en/latest/topics/examples.html)
but the configuration does not seem to be accepted.
