### ISSUE TITLE
Launch with cloud-init times out when installing snaps

### ISSUE THREAD

**Issue by AlbertoDePena** [canonical/multipass#1488]
Using multipass in Windows 10 Enterprise (1903) and trying to launch a vm with cloud-init. 

I want to install docker and microk8s at the same time. I have no problem installing docker but once I include the snap command to install microk8s, the multipass launch command takes a while, then finished saying timeout error.  Im sure Im just messing up the cloud-init confi. Any help would be appreciated =)

```bash
multipass launch --name microk8s-vm --mem 4G --disk 40G --cloud-init .\cloud-config.yml
```

Note: I commented out all the step that could be the problem. 

```yaml
#cloud-config

package_update: true
package_upgrade: true
package_reboot_if_required: true

users:
- name: ubuntu
  shell: /bin/bash
  sudo:
    - ALL=(ALL) NOPASSWD:ALL

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common
  #- iptables-persistent

runcmd:
  # install docker
  - sudo apt update -y && sudo apt upgrade -y
  - sudo apt install -y apt-transport-https ca-certificates curl software-properties-common
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
  - sudo apt update -y
  - sudo apt install -y docker-ce
  - sudo usermod -aG docker ubuntu
  # install microk8s
  #- sudo snap install microk8s --classic --channel=1.18/stable
  #- sudo iptables -P FORWARD ACCEPT
  #- sudo usermod -a -G microk8s ubuntu
  #- sudo chown -f -R ubuntu ~/.kube
  #- sudo echo "{ \"insecure-registries\" : [\"localhost:32000\"] }" > /etc/docker/daemon.json
  #- echo iptables-persistent iptables-persistent/autosave_v4 boolean true | sudo debconf-set-selections
  #- echo iptables-persistent iptables-persistent/autosave_v6 boolean true | sudo debconf-set-selections
  #- sudo apt install -y iptables-persistent
  
final_message: "The system is finally up, after $UPTIME seconds"
```
