### ISSUE TITLE
Multipass to honour system_info.default_user on Windows 10 + Hyper V

### ISSUE THREAD

**Issue by fquinner** [canonical/multipass#1631]
**What are you trying to do?**
Create a multipass instance with an alternative user to "ubuntu" so that "exec" commands can be run as the alternative default user name.

**What's your proposed solution?**
A configurable user in multipass is used

**Additional context**
I ran with this:

```
users:
  - name: fquinn
    ssh_authorized_keys:
      - <my pub key>
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    
system_info:
  default_user:
    name: fquinn
```

And I can ssh into it from windows fine (using my default ssh private key), but when i tail the guest's log, I can see that the multipass exec commands try to use the ubuntu user explicitly:

```
Jul 04 17:35:45 test3 sshd[2650]: Invalid user ubuntu from 172.24.160.1 port 56706
Jul 04 17:35:45 test3 sshd[2650]: Connection closed by invalid user ubuntu 172.24.160.1 port 56706 [preauth]
```
