### ISSUE TITLE
[lxd] daemon fails to realize instance didn't start

### ISSUE THREAD

**Issue by Saviq** [canonical/multipass#1772]
LXD stopped starting instances here for some reason. Multipass just spits out:
```json
[2020-09-30T19:24:12.736] [trace] [snapcraft-egmde-confined-desktop] Got LXD container state: snapcraft-egmde-confined-desktop is Stopped
[2020-09-30T19:24:12.736] [trace] [lxd request] Requesting LXD: PUT unix://multipass/var/snap/lxd/common/lxd/unix.socket@1.0/virtual-machines/snapcraft-egmde-confined-desktop/state?project=multipass
[2020-09-30T19:24:12.736] [trace] [lxd request] Sending data: {"action":"start"}
[2020-09-30T19:24:12.755] [trace] [lxd request] Got reply: {
    "error": "",
    "error_code": 0,
    "metadata": {
        "class": "task",
        "created_at": "2020-09-30T19:24:12.738829524+02:00",
        "description": "Starting container",
        "err": "",
        "id": "b95d2df7-2754-4a06-918f-f7e78aedf068",
        "location": "none",
        "may_cancel": false,
        "metadata": null,
        "resources": {
            "containers": [
                "/1.0/containers/snapcraft-egmde-confined-desktop"
            ]
        },
        "status": "Running",
        "status_code": 103,
        "updated_at": "2020-09-30T19:24:12.738829524+02:00"
    },
    "operation": "/1.0/operations/b95d2df7-2754-4a06-918f-f7e78aedf068",
    "status": "Operation created",
    "status_code": 100,
    "type": "async"
}
start failed: The following errors occurred:
failed to determine IP address
```
`lxc monitor` output ([full here](https://github.com/canonical/multipass/files/5307262/lxc-monitor.txt)) shows there's been an error starting the instance:
```yaml
location: none
metadata:
  context:
    ip: '@'
    method: PUT
    url: /1.0/virtual-machines/snapcraft-egmde-confined-desktop/state?project=multipass
    user: ""
  level: dbug
  message: Handling
timestamp: "2020-09-30T19:24:12.737442421+02:00"
type: logging

location: none
metadata:
  context: {}
  level: dbug
  message: 'New task Operation: b95d2df7-2754-4a06-918f-f7e78aedf068'
timestamp: "2020-09-30T19:24:12.753362227+02:00"
type: logging

location: none
metadata:
  context: {}
  level: dbug
  message: 'Started task operation: b95d2df7-2754-4a06-918f-f7e78aedf068'
timestamp: "2020-09-30T19:24:12.7542144+02:00"
type: logging

# ...

location: none
metadata:
  context: {}
  level: dbug
  message: |-
    Failure for task operation: b95d2df7-2754-4a06-918f-f7e78aedf068: Failed to run: forklimits limit=memlock:unlimited:unlimited
-- /snap/lxd/17320/bin/qemu-system-x86_64 -S -name snapcraft-egmde-confined-desktop -uuid 598bce0e-ff89-4d7a-860e-df4b2f66298b -da
emonize -cpu host -nographic -serial chardev:console -nodefaults -no-reboot -no-user-config -sandbox on,obsolete=deny,elevateprivi
leges=allow,spawn=deny,resourcecontrol=deny -readconfig /var/snap/lxd/common/lxd/logs/multipass_snapcraft-egmde-confined-desktop/q
emu.conf -pidfile /var/snap/lxd/common/lxd/logs/multipass_snapcraft-egmde-confined-desktop/qemu.pid -D /var/snap/lxd/common/lxd/lo
gs/multipass_snapcraft-egmde-confined-desktop/qemu.log -chroot /var/snap/lxd/common/lxd/virtual-machines/multipass_snapcraft-egmde
-confined-desktop -smbios type=2,manufacturer=Canonical Ltd.,product=LXD -runas lxd: qemu-system-x86_64: cannot create PID file: C
annot lock pid file: Resource temporarily unavailable
    : Process exited with a non-zero value
timestamp: "2020-09-30T19:24:23.060179663+02:00"
type: logging
```
