### ISSUE TITLE
[lxd] profile missing the `root` device

### ISSUE THREAD

**Issue by Saviq** [canonical/multipass#1774]
Not sure how this came to be, but my `default` profile in the `multipass` project lost its `root` device:
```yaml
 lxc profile show default --project multipass
config: {}
description: Default profile for Multipass project
devices:
  eth0:
    name: eth0
    nictype: bridged
    parent: mpbr0
    type: nic
name: default
used_by:
- /1.0/instances/snapcraft-egmde-confined-desktop?project=multipass
```

Launching instances fails without a good error message:
```
launch failed: unix://multipass/var/snap/lxd/common/lxd/unix.socket@1.0/virtual-machines?project=multipass: Bad Request
```

[lxc-monitor-edge.log](https://github.com/canonical/multipass/files/5310183/lxc-monitor-edge.log)
[multipass-launch-edge.txt](https://github.com/canonical/multipass/files/5310184/multipass-launch-edge.txt)
