### ISSUE TITLE
ssh failed to authenticate: 'Access denied for 'publickey'. Authentication that can continue: publickey'

### ISSUE THREAD

**Issue by tanthdyn** [canonical/multipass#1852]
Hi

I made a change to authorized_keys by adding a new public key with passphrase for ubuntu@local.
Can I recover from this issues ?

multipass version :
multipass  1.4.0+win
multipassd 1.4.0+win

Thanks a lot
Tony

**Comment by Saviq** [comment]
Hi @tanthdyn, can you ssh to the instance with your new key?

**Comment by maksimyugai** [comment]
Have the same issue, but I've just mounted local .ssh/ dir to instance /home/ubuntu/.ssh.
multipass 1.6.2
multipassd 1.6.2

**Comment by Saviq** [comment]
> Have the same issue, but I've just mounted local .ssh/ dir to instance /home/ubuntu/.ssh.

This will almost surely break `multipass shell`, and subsequent mounts themselves…

**Comment by Saviq** [comment]
I'm going to close this since we didn't get feedback from the original reporter.

**Comment by jobechoi** [comment]
@Saviq I'm just learning. The --cloud-init sort of "failed" I can see the instance running. Yet when I make a go at launching the shell: "ssh failed to authenticate: 'Access denied for 'publickey'. Authentication that can continue: publickey'"

I know it would be worth figuring this out with the folks on the issue. Or, f* learning and just try over.

**Comment by Saviq** [comment]
@jobechoi can you please file a new issue and provide steps to reproduce, logs etc.?

**Comment by osys** [comment]
> 
I also encountered the same problem. I tried many times to no avail.

My command to create an instance is this:
`multipass launch bionic --name c1gm1gd5g1804 -c 1 -m 1g -d 5g --cloud-init cloud-init.yaml`
output some information：
```
launch failed: The following errors occurred:
timed out waiting for initialization to complete
```

View instance list `multipass list`.
able to get this information：
```
Name                    State             IPv4             Image
c1gm1gd5g1804           Running           192.168.137.48   Ubuntu 18.04 LTS
```

Then I execute the command `multipass shell c1gm1gd5g1804`.
get this result:
```
shell failed: ssh failed to authenticate: 'Access denied for 'publickey'. Authentication that can continue: publickey,password'
```

If I use the `ssh lyh@192.168.137.48` command to connect to the instance, I am able to connect.
```
The authenticity of host '192.168.137.48 (192.168.137.48)' can't be established.
ECDSA key fingerprint is SHA256:zjR******************************M.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '192.168.137.48' (ECDSA) to the list of known hosts.
Welcome to Ubuntu 18.04.6 LTS (GNU/Linux 4.15.0-200-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Mon Jan  9 18:05:08 CST 2023

  System load:  0.0               Processes:           83
  Usage of /:   23.9% of 4.67GB   Users logged in:     0
  Memory usage: 15%               IP address for eth0: 192.168.137.48
  Swap usage:   0%

0 updates can be applied immediately.



The programs included with the Ubuntu system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by
applicable law.

To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

lyh@c1gm1gd5g1804:~$
```

My cloud-init.yaml file content is like this:
```
groups:
  - admingroup: [root, sys]
  - cloud-users

system_info:
  default_user:
    name: lyh
    plain_text_passwd: '123456'
    home: /home/lyh
    shell: /bin/bash
    lock_passwd: false
    gecos: lyh
    groups: [root, admin]
    ssh_authorized_keys:
      - "ssh-rsa *************************************"

users:
  - default
  - name: demo
    gecos: test
    primary_group: demo
    groups: users
    expiredate: '2032-09-01'
    lock_passwd: false
    # password is 123456
    passwd: $1$EHfKvyKM$xwlR8OHVWquIfOBEqTB7s/
    ssh_authorized_keys:
      - "ssh-rsa *************************************"
    sudo: ALL=(ALL) NOPASSWD:ALL

ssh_pwauth: true
```

This problem is very strange, I don't know how to solve it.
