### ISSUE TITLE
Big sur showing list failed: cannot connect to the multipass socket Please ensure multipassd is running and '/var/run/multipass_socket' is accessible

### ISSUE THREAD

**Issue by dmuiX** [canonical/multipass#1983]
**Describe the bug**
I have closed multipassd forcefully with the activity view thing. I don't know how its called correctly in english. Now multipass list is now showing:
```
list failed: cannot connect to the multipass socket
Please ensure multipassd is running and '/var/run/multipass_socket' is accessible
```
The only thing how to get it working again was for me so far to completely delete everything. Maybe there is another way?

**My overall impression so far:***
Have used it for a while now and my impression is its not quite stable on mac big sur. After digging around with it a while I am getting more annoyed of it as its not really providing value for me with these errors. Hopefully getting better in the future as I think its a quite good software.

**Comment by Saviq** [comment]
@dmuiX if you forcefully shut it down, there's a chance our data storage got corrupted. Can you please share the contents of your `multipassd.log`? See [accessing logs](https://multipass.run/docs/accessing-logs#macos) for instructions on where to find it.

**Comment by dmuiX** [comment]
[multipassd.log](https://github.com/canonical/multipass/files/6044077/multipassd.log)

**Comment by dmuiX** [comment]
Thanks for responding so fast :)

**Comment by dmuiX** [comment]
> @dmuiX if you forcefully shut it down, there's a chance our data storage got corrupted. Can you please share the contents of your `multipassd.log`? See [accessing logs](https://multipass.run/docs/accessing-logs#macos) for instructions on where to find it.

What is the correct way to shut multipass down if something is wrong or not responding?

**Comment by Saviq** [comment]
This should do:
```
$ sudo launchctl unload /Library/LaunchDaemons/com.canonical.multipassd.plist
$ sudo launchctl load /Library/LaunchDaemons/com.canonical.multipassd.plist
```

But it may well result in the same problem, if multipassd got stuck somehow.

I can see in the log why it never came up again:
```plain
[error] [daemon] Caught an unhandled exception: Invalid MAC address
```

Can you please share the contents of `/var/root/Library/Application Support/multipassd/multipassd-vm-instances.json`?

**Comment by dmuiX** [comment]
```yaml
{
    "ubuntu": {
        "deleted": false,
        "disk_space": "0",
        "extra_interfaces": [
        ],
        "mac_addr": "",
        "mem_size": "0",
        "metadata": {
        },
        "mounts": [
        ],
        "num_cores": 0,
        "ssh_username": "",
        "state": 2
    },
    "ubuntuVM": {
        "deleted": false,
        "disk_space": "5368709120",
        "extra_interfaces": [
        ],
        "mac_addr": "52:54:00:19:23:bc",
        "mem_size": "1073741824",
        "metadata": {
        },
        "mounts": [
            {
                "gid_mappings": [
                    {
                        "host_gid": 20,
                        "instance_gid": -1
                    }
                ],
                "source_path": "/Volumes/Data/Computerspende/computerspende",
                "target_path": "~/computerspende",
                "uid_mappings": [
                    {
                        "host_uid": 501,
                        "instance_uid": -1
                    }
                ]
            },
            {
                "gid_mappings": [
                    {
                        "host_gid": 20,
                        "instance_gid": -1
                    }
                ],
                "source_path": "/Volumes/Data/Computerspende/computerspende",
                "target_path": "/Volumes/Data/Computerspende/computerspende",
                "uid_mappings": [
                    {
                        "host_uid": 501,
                        "instance_uid": -1
                    }
                ]
            }
        ],
        "num_cores": 1,
        "ssh_username": "ubuntu",
        "state": 4
    }
}{
    "ubuntu": {
        "deleted": false,
        "disk_space": "0",
        "extra_interfaces": [
        ],
        "mac_addr": "",
        "mem_size": "0",
        "metadata": {
        },
        "mounts": [
        ],
        "num_cores": 0,
        "ssh_username": "",
        "state": 2
    },
    "ubuntuVM": {
        "deleted": false,
        "disk_space": "5368709120",
        "extra_interfaces": [
        ],
        "mac_addr": "52:54:00:19:23:bc",
        "mem_size": "1073741824",
        "metadata": {
        },
        "mounts": [
            {
                "gid_mappings": [
                    {
                        "host_gid": 20,
                        "instance_gid": -1
                    }
                ],
                "source_path": "/Volumes/Data/Computerspende/computerspende",
                "target_path": "~/computerspende",
                "uid_mappings": [
                    {
                        "host_uid": 501,
                        "instance_uid": -1
                    }
                ]
            },
            {
                "gid_mappings": [
                    {
                        "host_gid": 20,
                        "instance_gid": -1
                    }
                ],
                "source_path": "/Volumes/Data/Computerspende/computerspende",
                "target_path": "/Volumes/Data/Computerspende/computerspende",
                "uid_mappings": [
                    {
                        "host_uid": 501,
                        "instance_uid": -1
                    }
                ]
            }
        ],
        "num_cores": 1,
        "ssh_username": "ubuntu",
        "state": 4
    }
}
```

**Comment by dmuiX** [comment]
Actually I deleted ubuntu and ubuntuTest

**Comment by dmuiX** [comment]
Everytime I have tried multipass purge so far it ended with taking very long time. And then I stopped it with ctrl+c or last time with the activity thing and then when I ran multipass list it showed the error above.

**Comment by dmuiX** [comment]
I remember a detail now: 
These two VMs I wanted to delete ubuntu and ubuntuTest did not start properly in the first place. They just stood on starting the whole time not showing anything. 
I am trying to create vms with a cloud-init file.

**Comment by dmuiX** [comment]
How is it possible to get more output with these commands? If i try -vvvv nothing changes.

**Comment by dmuiX** [comment]
> This should do:
> 
> ```
> $ sudo launchctl unload /Library/LaunchDaemons/com.canonical.multipassd.plist
> $ sudo launchctl load /Library/LaunchDaemons/com.canonical.multipassd.plist
> ```
> 
> But it may well result in the same problem, if multipassd got stuck somehow.
> 
> I can see in the log why it never came up again:
> 
> ```
> [error] [daemon] Caught an unhandled exception: Invalid MAC address
> ```
> 
> Can you please share the contents of `/var/root/Library/Application Support/multipassd/multipassd-vm-instances.json`?
> 
> Unfortunately I can't see what went wrong in the first place… Everything seems ok right up to the above errors, at which point I imagine you killed it.

about the restart => Yeah it ends in the same error again.

**Comment by Saviq** [comment]
OK, to recover, `unload`, replace the contents of the json file with the below, and `load` again.

```json
{
    "ubuntuVM": {
        "deleted": false,
        "disk_space": "5368709120",
        "extra_interfaces": [
        ],
        "mac_addr": "52:54:00:19:23:bc",
        "mem_size": "1073741824",
        "metadata": {
        },
        "mounts": [
            {
                "gid_mappings": [
                    {
                        "host_gid": 20,
                        "instance_gid": -1
                    }
                ],
                "source_path": "/Volumes/Data/Computerspende/computerspende",
                "target_path": "~/computerspende",
                "uid_mappings": [
                    {
                        "host_uid": 501,
                        "instance_uid": -1
                    }
                ]
            },
            {
                "gid_mappings": [
                    {
                        "host_gid": 20,
                        "instance_gid": -1
                    }
                ],
                "source_path": "/Volumes/Data/Computerspende/computerspende",
                "target_path": "/Volumes/Data/Computerspende/computerspende",
                "uid_mappings": [
                    {
                        "host_uid": 501,
                        "instance_uid": -1
                    }
                ]
            }
        ],
        "num_cores": 1,
        "ssh_username": "ubuntu",
        "state": 4
    }
}
```

That should bring `ubuntuVM` back.

**Comment by Saviq** [comment]
> I am trying to create vms with a cloud-init file. Maybe it has something to do with these files?

Yes, if it failed to boot properly (or just failed to get IP), that's likely to be the result of that. If you can show me what the cloud init was, I can maybe suggest what's wrong with them.

And yes, we're not exactly great dealing with unresponsive VMs… there's a couple issues we have around and we're planning a `--force` option to `stop` and `delete` that would not try and shut the VM down cleanly, but just killed it.

**Comment by dmuiX** [comment]
> > I am trying to create vms with a cloud-init file. Maybe it has something to do with these files?
> 
> Yes, if it failed to boot properly (or just failed to get IP), that's likely to be the result of that. If you can show me what the cloud init was, I can maybe suggest what's wrong with them.
> 
> And yes, we're not exactly great dealing with unresponsive VMs… there's a couple issues we have around and we're planning a `--force` option to `stop` and `delete` that would not try and shut the VM down cleanly, but just killed it.

So at the moment its not really possible to shut a not responding vm down properly? Or do you know a way to do it properly?
As I am experimenting with these cloud-init files i don't want to reinstall multipass if something goes wrong.
Oh I just saw: Can I first do stop and then delete everything should be fine?

**Comment by dmuiX** [comment]
> OK, to recover, `unload`, replace the contents of the json file with the below, and `load` again.
> 
> ```json
> {
>     "ubuntuVM": {
>         "deleted": false,
>         "disk_space": "5368709120",
>         "extra_interfaces": [
>         ],
>         "mac_addr": "52:54:00:19:23:bc",
>         "mem_size": "1073741824",
>         "metadata": {
>         },
>         "mounts": [
>             {
>                 "gid_mappings": [
>                     {
>                         "host_gid": 20,
>                         "instance_gid": -1
>                     }
>                 ],
>                 "source_path": "/Volumes/Data/Computerspende/computerspende",
>                 "target_path": "~/computerspende",
>                 "uid_mappings": [
>                     {
>                         "host_uid": 501,
>                         "instance_uid": -1
>                     }
>                 ]
>             },
>             {
>                 "gid_mappings": [
>                     {
>                         "host_gid": 20,
>                         "instance_gid": -1
>                     }
>                 ],
>                 "source_path": "/Volumes/Data/Computerspende/computerspende",
>                 "target_path": "/Volumes/Data/Computerspende/computerspende",
>                 "uid_mappings": [
>                     {
>                         "host_uid": 501,
>                         "instance_uid": -1
>                     }
>                 ]
>             }
>         ],
>         "num_cores": 1,
>         "ssh_username": "ubuntu",
>         "state": 4
>     }
> }
> ```
> 
> That should bring `ubuntuVM` back.

And multipass list is working again?

**Comment by dmuiX** [comment]
Thanks a lot for helping out :)

**Comment by dmuiX** [comment]
Don't know if you need it but here is the output of
```
multipass info --all
```
```yaml
Name:           ubuntuVM
State:          Running
IPv4:           192.168.236.11
                172.17.0.1
Release:        Ubuntu 20.04.2 LTS
Image hash:     c5f2f08c6a1a (Ubuntu 20.04 LTS)
Load:           1.21 0.29 0.10
Disk usage:     2.7G out of 4.7G
Memory usage:   195.4M out of 981.4M
Mounts:         /Volumes/Data/Computerspende/computerspende => /Volumes/Data/Computerspende/computerspende
                    UID map: 501:default
                    GID map: 20:default
                /Volumes/Data/Computerspende/computerspende => ~/computerspende
                    UID map: 501:default
                    GID map: 20:default
```

**Comment by Saviq** [comment]
So this is at least part of the problem:
```yaml
users:
  - default
  - name: ubuntu
    ssh_authorized_keys:
      - ssh-rsa <somekey>
...
```

We rely on the `default` user to manage the VM, and doing this you're replacing Multipass's SSH key, so we lose connectivity to the instance. We plan to drop that requirement, but didn't get around to it just yet.

It'd be safest if you used a custom user instead.

**Comment by dmuiX** [comment]
Thats weird.
The ubuntuVM above I have created with a pretty similiar cloud-init file. And it was running just fine.
```yaml
#cloud-config
groups:
  - docker

users:
  - default
  - name: ubuntu
    groups: docker
    sudo:  ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC1+Ji93zXpPqYjFUVWmNWooqUBwAbc0zUefCZVzP012RXgDQAR2LZtr6t1Yx35/jr4E9oBFvCFHvMBmUpmQEIehLb7RR4ksSdmEEQB3QHqlS0fTmEdnrjg3pgVOuXYKVySGoyiUPaVo5wV/lcyLD2xZQaXWKtu25bn+EaE9Eo58TnvEHiVWyf0avgUXx6xoXpuy0n3VFZ3QXSq1ll7wmEzfxOEIBqDJVkfVGJA9bUdYY05kEq5IZhLMxyyKFgCdYwhDau7HCkBwkhuJoM2RZYNaCoiIU2+hmirYtkvXdz8agiXhzqThYYPJUE2+Ash2sUMoQtWxS7LxkW/7EXKtW/3

package_upgrade: true

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common

runcmd:
  # install docker following the guide: https://docs.docker.com/install/linux/docker-ce/ubuntu/
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get -y update
  - sudo apt-get -y install docker-ce docker-ce-cli containerd.io
  - sudo systemctl enable docker
  # install docker-compose following the guide: https://docs.docker.com/compose/install/
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose

power_state:
  mode: reboot
  message: Restarting after installing docker & docker-compose
```
But I am runnning another launch with this config again at the moment. Maybe it was just luck :D.

**Comment by dmuiX** [comment]
Maybe it has something to do if I start another instance of the same image although the other instance is still running?
I am trying now the first file from above. And will report what happens.

**Comment by Saviq** [comment]
>  Oh I just saw: Can I first do stop and then delete everything should be fine?

Killing the `hyperkit` process is safest. That would make Multipass realize it's gone.

**Comment by Saviq** [comment]
> The ubuntuVM above I have created with a pretty similiar cloud-init file. And it was running just fine.

Oh indeed, it concatenates the SSH keys :]

**Comment by Saviq** [comment]
FWIW I just launched with your "full" cloud init, and it launched fine, so it must be some bad luck on those that failed to start…

**Comment by dmuiX** [comment]
> > The ubuntuVM above I have created with a pretty similiar cloud-init file. And it was running just fine.
> 
> Oh indeed, it concatenates the SSH keys :]
so this is the correct way to add ssh-keys?

**Comment by Saviq** [comment]
> so this is the correct way to add ssh-keys?

Yes, I can't see anything wrong with your cloud-init after all.

Well, except for this, but that won't prevent Multipass from working :)
```plain
The following packages have unmet dependencies:
 containerd.io : Depends: libc6 (>= 2.32) but 2.31-0ubuntu9.2 is to be installed
 docker-ce : Depends: libc6 (>= 2.32) but 2.31-0ubuntu9.2 is to be installed
             Recommends: docker-ce-rootless-extras but it is not going to be installed
             Recommends: pigz but it is not going to be installed
 docker-ce-cli : Depends: libc6 (>= 2.32) but 2.31-0ubuntu9.2 is to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by dmuiX** [comment]
> FWIW I just launched with your "full" cloud init, and it launched fine, so it must be some bad luck on those that failed to start…
I am not that lucky now.
I am running two vms now one with the first file and the second with the second file. Both vms started but they are both are stucked at starting...

**Comment by dmuiX** [comment]
> > so this is the correct way to add ssh-keys?
> 
> Yes, I can't see anything wrong with your cloud-init after all.
> 
> Well, except for this, but that won't prevent Multipass from working :)
> 
> ```
> The following packages have unmet dependencies:
>  containerd.io : Depends: libc6 (>= 2.32) but 2.31-0ubuntu9.2 is to be installed
>  docker-ce : Depends: libc6 (>= 2.32) but 2.31-0ubuntu9.2 is to be installed
>              Recommends: docker-ce-rootless-extras but it is not going to be installed
>              Recommends: pigz but it is not going to be installed
>  docker-ce-cli : Depends: libc6 (>= 2.32) but 2.31-0ubuntu9.2 is to be installed
> E: Unable to correct problems, you have held broken packages.
> ```

is this output from the vm? how did you get this?

**Comment by Saviq** [comment]
> is this output from the vm? how did you get this?

This is from cloud-init logs at `/var/logs/cloud-init-output.log` inside the VM.

**Comment by Saviq** [comment]
> I am not that lucky now.
> I am running two vms now one with the first file and the second with the second file. Both vms started but they are both are stucked at starting...

There's two places you could look for what went wrong:
1. `/Library/Logs/Multipass/<name>-hyperkit.log` has the console output of the VMs, it could suggest what the problem was
2. `sudo screen /var/root/Library/Application\ Support/multipassd/vault/instances/<name>/pty` would let you connect to the console of the VM

**Comment by Saviq** [comment]
I just ran this and it worked fine:

```yaml
$ multipass launch --cloud-init - <<EOF                             
#cloud-config
groups:
  - docker

users:
  - default
  - name: ubuntu
    groups: docker
    sudo:  ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
      - ssh-rsa $( cat ~/.ssh/id_rsa.pub )

package_upgrade: true

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common

runcmd:
  # install docker following the guide: https://docs.docker.com/install/linux/docker-ce/ubuntu/
  - curl -sSL https://get.docker.com/ | sh
  # install docker-compose following the guide: https://docs.docker.com/compose/install/
  - sudo curl -L "https://github.com/docker/compose/releases/download/1.25.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - sudo chmod +x /usr/local/bin/docker-compose

power_state:
  mode: reboot
  message: Restarting after installing docker & docker-compose
EOF
```
