### ISSUE TITLE
Unexpected partitioning and rootfs size

### ISSUE THREAD

**Issue by Saviq** [canonical/multipass#2049]
By using the  MULTIPASS_STORAGE workaround, I get VMs with strange partitioning and /  (root) partitions of many GBs less than the disk size I provide through args. This happens in win10 hosts, multipass 1.6.2 with Hyper-V and 18.04 guests. I haven't tested it with 20.04 guests before reverting back to the default location.

_Originally posted by @devspyrosv in https://github.com/canonical/multipass/issues/1112#issuecomment-817049151_

**Comment by Saviq** [comment]
@devspyrosv hey, could you provide some more context? How did you `launch` the instance, what's the output of `info`?

**Comment by devspyrosv** [comment]
> 
> 
> @devspyrosv hey, could you provide some more context? How did you `launch` the instance, what's the output of `info`?

The command was this:

```multipass launch --cpus 2 --disk 40G --mem 20G --name renderer1 --network "name=Bridge Switch" --cloud-init C:\Users\Drake\Documents\multipass\cloud-init-renderer1.yml bionic```

This created a root partition of 4 or 10 GBs only. The remaining storage was split between /tmp and some other partitions.

The cloud-init file: 

```
#cloud-init-crawler.yml
# Apt
package_update: true
package_upgrade: true
package_reboot_if_required: true
# Resolv/DNS
manage_resolv_conf: true
resolv_conf:
    nameservers: ['192.168.1.100']          
    domain: home.internal    
# Hostname
preserve_hostname: false
hostname: renderer1
# Final reboot
power_state:
  delay: "now"
  mode: reboot
  timeout: 30
```

Unfortunately I didn't save the info output and I have no way to test it in the foreseeable future using MULTIPASS_STORAGE again.
