### ISSUE TITLE
[feature] Add a command section to Blueprints

### ISSUE THREAD

**Issue by townsend2010** [canonical/multipass#2175]
@townsend2010 have you thought of adding a command section to the workflow?  I've written a tool which behaves similarly to a workflow, with the exception of command execution sections. 

An example workflow:

* Boot multipass VM
* Install k3s via cloud init
* Copy kubeconfig to system invoking multipass `multipass transfer <instance>:/etc/rancher/k3s/k3s.yaml /local/path/k3s.yaml`
* Enable regcred acces to docker instance `multipass exec <instance> sudo docker login <registry_server> -u $ENV[user] -p ENV[pass]`
* Create k8s regcred secret `sudo kubectl create secret generic regcred --from-file=.dockerconfigjson=/root/.docker/config.json --type=kubernetes.io/dockerconfigjson`

The point being there may be lightweight orchestration events that would be helpful to run on create and outside cloud-init.

```
description: <string>      # * a short description of the workflow ("tagline")
version: <string>          # * a version string

instances:
  <name>:                  # * equal to the workflow name
    image: <base image>    # a valid image alias, see `multipass find` for available values
    limits:
      min-cpu: <int>       # the minimum number of CPUs this workflow can work with
      min-mem: <string>    # the minimum amount of memory (can use G/K/M/B suffixes)
      min-disk: <string>   # and the minimum disk size (as above)
    timeout: <int>         # maximum time for the instance to launch, and separately for cloud-init to complete
    cloud-init:
      vendor-data: |       # cloud-init vendor data
        <string>
    commands:
      <string>             # string of shell commands to be executed locally by the user invoking multipass.
```

_Originally posted by @retr0h in https://github.com/canonical/multipass/issues/2040#issuecomment-880845292_
