### ISSUE TITLE
Support changing default user via cloud-init

### ISSUE THREAD

**Issue by derust** [canonical/multipass#2329]
when change default user use cloudinit,
`multipass shel`l (also `multipass exec`) will fail, with message
```
shell failed: ssh failed to authenticate: 'Access denied for 'publickey'. Authentication that can continue: publickey'
```

#### launch 
```sh
multipass launch instance use --cloud-init cloud-config.yaml
```

#### cloud-config.yaml
```
system_info:
   default_user:
     name: admin
     lock_passwd: true
     groups: users, admin
     sudo: ["ALL=(ALL) NOPASSWD:ALL"]
     shell: /bin/bash
     passwd: $6$xxxxxxe.
```
