### ISSUE TITLE
Multipass assigns the same IP address to multiple VMs when used by snapcraft

### ISSUE THREAD

**Issue by geekorous** [canonical/multipass#2366]
**Describe the bug**
Describe what your problem is.
When attempting to run multiple snapcraft builds concurrently, the spawned VMs are allocated the same IP address by the bridge, resulting in the crash of both VMs.

**Expected behavior**
What did you expect to happen?
Assign the last unassigned address to each VM in a reliable manner.

**Logs**
Please provide logs from the daemon, see [accessing logs](https://multipass.run/docs/accessing-logs) on where to find them on your platform.

I guess this portion of the log is more important:

```
Dec 05 21:18:23 lamborghini dnsmasq-dhcp[3981]: DHCPDISCOVER(mpqemubr0) 52:54:00:97:a4:f9
Dec 05 21:18:23 lamborghini dnsmasq-dhcp[3981]: DHCPOFFER(mpqemubr0) 10.30.202.107 52:54:00:97:a4:f9
Dec 05 21:18:23 lamborghini dnsmasq-dhcp[3981]: DHCPDISCOVER(mpqemubr0) 52:54:00:97:a4:f9
Dec 05 21:18:23 lamborghini dnsmasq-dhcp[3981]: DHCPOFFER(mpqemubr0) 10.30.202.107 52:54:00:97:a4:f9
Dec 05 21:18:23 lamborghini dnsmasq-dhcp[3981]: DHCPREQUEST(mpqemubr0) 10.30.202.107 52:54:00:97:a4:f9
Dec 05 21:18:23 lamborghini dnsmasq-dhcp[3981]: DHCPACK(mpqemubr0) 10.30.202.107 52:54:00:97:a4:f9 snapcraft-app-1
Dec 05 21:18:25 lamborghini multipassd[2303]: QMP: {"timestamp": {"seconds": 1638735505, "microseconds": 227385}, "event": "NIC_RX_FILTER_CHANGED", "data": {"path": "/machine/unattached/dev>
Dec 05 21:18:25 lamborghini dnsmasq-dhcp[3981]: DHCPDISCOVER(mpqemubr0) 52:54:00:9b:5f:12
Dec 05 21:18:25 lamborghini dnsmasq-dhcp[3981]: DHCPOFFER(mpqemubr0) 10.30.202.107 52:54:00:9b:5f:12
Dec 05 21:18:25 lamborghini dnsmasq-dhcp[3981]: DHCPREQUEST(mpqemubr0) 10.30.202.107 52:54:00:9b:5f:12
Dec 05 21:18:25 lamborghini dnsmasq-dhcp[3981]: DHCPACK(mpqemubr0) 10.30.202.107 52:54:00:9b:5f:12 snapcraft-app-2

```

**Additional info**
 - OS: [e.g. macOS 10.15]
- `multipass version`: 1.8.0
- `multipass info --all`
```
Name:           snapcraft-app-2
State:          Unknown
IPv4:           --
Release:        --
Image hash:     7c5c8f24046c (Ubuntu Snapcraft builder for Core 18)
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --

Name:           snapcraft-app-1
State:          Running
IPv4:           10.30.202.140
Release:        Ubuntu 18.04.5 LTS
Image hash:     7c5c8f24046c (Ubuntu Snapcraft builder for Core 18)
Load:           0.08 0.06 0.02
Disk usage:     953.6M out of 19.2G
Memory usage:   48.7M out of 5.8G
Mounts:         --
```

**Comment by townsend2010** [comment]
Hey @geekorous,

This looks really strange. It kind of looks like `dnsmasq` didn't do the right thing.  Is this easily reproducible for you or is it a one off?  Also, I think it would be helpful if you could provide more of the logs and also provide the contents of `/var/snap/multipass/common/data/multipassd/network/dnsmasq.leases`.

Thanks!

**Comment by geekorous** [comment]
Hey @townsend2010,

I could easily reproduce the issue from scratch. I create two directories, `snap-1` and `snap-2`, on both I run `snapcraft init`. I just edit the name of the snaps to come up with simple snapcraft files like this:

```
name: snap-1 # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  my-part:
    # See 'snapcraft plugins'
    plugin: nil

```
and similarly:

```
name: snap-2 # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  my-part:
    # See 'snapcraft plugins'
    plugin: nil
```

Then I run `snapcraft` in each directory. Running `multipass list` hangs up and doesn't respond. However, since I use LXD as the backend, I could retrieve the info from `lxc list --project multipass`:

```
+------------------+---------+----------------------+---------------------------------------------+-----------------+-----------+
|       NAME       |  STATE  |         IPV4         |                    IPV6                     |      TYPE       | SNAPSHOTS |
+------------------+---------+----------------------+---------------------------------------------+-----------------+-----------+
| snapcraft-snap-1 | RUNNING | 10.48.209.209 (eth0) | fd42:d52f:dc55:5f8:5054:ff:fe35:9726 (eth0) | VIRTUAL-MACHINE | 0         |
+------------------+---------+----------------------+---------------------------------------------+-----------------+-----------+
| snapcraft-snap-2 | RUNNING | 10.48.209.209 (eth0) | fd42:d52f:dc55:5f8:5054:ff:fe7a:bd9 (eth0)  | VIRTUAL-MACHINE | 0         |
+------------------+---------+----------------------+---------------------------------------------+-----------------+-----------+
```

Depending on the progress of the first build when you execute the second one, either you receive:
```
An error occurred when trying to execute 'sudo -H -i env SNAPCRAFT_BUILD_ENVIRONMENT=managed-host HOME=/root SNAPCRAFT_HAS_TTY=True apt-get dist-upgrade --yes' with 'multipass': returned exit code 255.
```
or it stalls forever. In the second case I guess the issue avoids SSH to be setup properly since I could see the following in journal:

```
multipassd[102910]: Starting Multipass 1.8.0
multipassd[102910]: Daemon arguments: /snap/multipass/6130/bin/multipassd --verbosity debug --logger platform
multipassd[102910]: Using the 'default' storage pool.
multipassd[102910]: Reserving more disk space (274877906944 bytes) than available (115282710528 bytes)
multipassd[102910]: Creating instance with image id: a14b2e755caf397f73e8bf126428fd476cddca68d1f84a41260108a489043c48
multipassd[102910]: Using the 'default' storage pool.
multipassd[102910]: Reserving more disk space (274877906944 bytes) than available (114660392960 bytes)
multipassd[102910]: Creating instance with image id: a14b2e755caf397f73e8bf126428fd476cddca68d1f84a41260108a489043c48
multipassd[102910]: Waiting for SSH to be up
multipassd[102910]: Waiting for SSH to be up
```

The file `/var/snap/multipass/common/data/multipassd/network/dnsmasq.leases` has zero-bytes contents:
```
-rw-r--r-- 1 root root 0 Dec 28 02:43 /var/snap/multipass/common/data/multipassd/network/dnsmasq.leases
```
