### ISSUE TITLE
make `multipass list --format csv|json|yaml` output consistent

### ISSUE THREAD

**Issue by z0mbix** [canonical/multipass#2464]
**What are you trying to do?**
I am wrapping multipass in another tool and found some inconsistencies in the output of the `info` subcommand when using the `--format` flag. Without the format flag, list shows the image name, but when using --format it only shows the release, e.g.:

```
$ multipass list
Name                     State             IPv4             Image
primary                  Running           192.168.64.24    Ubuntu 20.04 LTS
bionic                   Stopped           --               Ubuntu 18.04 LTS
openvpn                  Running           192.168.64.15    Ubuntu 20.04 LTS
                                           192.168.254.1
ssh-audit-logger-bionic  Running           192.168.64.27    Ubuntu 18.04 LTS
ssh-audit-logger-focal   Running           192.168.64.28    Ubuntu 20.04 LTS
``` 

The output of `multipass list --format json`:

```json
{
    "list": [
        {
            "ipv4": [
                "192.168.64.28"
            ],
            "name": "ssh-audit-logger-focal",
            "release": "20.04 LTS",
            "state": "Running"
        },
        {
            "ipv4": [
                "192.168.64.15",
                "192.168.254.1"
            ],
            "name": "openvpn",
            "release": "20.04 LTS",
            "state": "Running"
        },
        {
            "ipv4": [
            ],
            "name": "bionic",
            "release": "18.04 LTS",
            "state": "Stopped"
        },
        {
            "ipv4": [
                "192.168.64.24"
            ],
            "name": "primary",
            "release": "20.04 LTS",
            "state": "Running"
        },
        {
            "ipv4": [
                "192.168.64.27"
            ],
            "name": "ssh-audit-logger-bionic",
            "release": "18.04 LTS",
            "state": "Running"
        }
    ]
}
```

It is the same for `csv`, `yaml`, and `json` output.

**What's your proposed solution?**
It would be good to output both the release and image in all formats.

**Additional context**
Other outputs for reference:

```csv
multipass list --format csv
Name,State,IPv4,IPv6,Release,AllIPv4
primary,Running,192.168.64.24,,20.04 LTS,"192.168.64.24"
bionic,Stopped,,,18.04 LTS,""
openvpn,Running,192.168.64.15,,20.04 LTS,"192.168.64.15,192.168.254.1"
ssh-audit-logger-bionic,Running,192.168.64.27,,18.04 LTS,"192.168.64.27"
ssh-audit-logger-focal,Running,192.168.64.28,,20.04 LTS,"192.168.64.28"
```

```yaml
primary:
  - state: Running
    ipv4:
      - 192.168.64.24
    release: 20.04 LTS
bionic:
  - state: Stopped
    ipv4:
      []
    release: 18.04 LTS
openvpn:
  - state: Running
    ipv4:
      - 192.168.64.15
      - 192.168.254.1
    release: 20.04 LTS
ssh-audit-logger-bionic:
  - state: Running
    ipv4:
      - 192.168.64.27
    release: 18.04 LTS
ssh-audit-logger-focal:
  - state: Running
    ipv4:
      - 192.168.64.28
    release: 20.04 LTS

```
