### ISSUE TITLE
cannot connect to the multipass socket

### ISSUE THREAD

**Issue by GogoFC** [canonical/multipass#2505]
Windows 11
v1.8.1

Error: 

```
PS C:\Users\Goran> multipass list
list failed: cannot connect to the multipass socket
Please ensure multipassd is running and 'localhost:50051' is accessible
```

So this is what  I did:

1. Tried out custom partitioning via user-data, partitions got created but other partitions showed, rebooted VM. VM got stuck couldn't delete or stop it, so I stopped it via Hyper-V manager. Rebooted.
2.  After reboot the error came up.
3.  Reinstalled Multipass, same thing.
4.  Reinstalled Multipass with deleting all of the data, one VM that was still running didn't get deleted, all of the VM's "placeholders' in Hyper-V GUI manager seemed like they exist even though they were deleted. 
5.  Stopped the VM and reinstalled Multipass, VM got deleted but error persisted, can not start multipassd.
6.   Can not reinstall Multipass, about time to Nuke this Installation of Windows soon anyway.
7.   Event Viewer shows nothing, well it shows 6000+ separate events, all fine one repetitve warning.
```
  [url downloader] Cannot retrieve headers for https://cdimage.ubuntu.com/ubuntu-core/16/stable/current/ubuntu-core-16-amd64.img.xz: Host cdimage.ubuntu.com not found  
```
8.  Attempted to start multipassd.exe manually got an error about forbidden D:, I don't have a D drive.  Had to record this, it's not in the Event Viewer. 

![Screenshot 2022-03-31 012113](https://user-images.githubusercontent.com/9360410/160948803-629a6a33-ea1b-438e-9937-b90345b6c117.png)

9.  Deleted leftovers from `%programfiles%` and `%appdata%`, there was some caches left over in Program Files, user appdata local and roaming. Still error persists after reinstall. 
10.  Installer now says "Daemon install result: 0"

Multipass GUI now runs twice, daemon doesn't start, GUI says failure to retrieve instances.

![Screenshot 2022-03-31 015222](https://user-images.githubusercontent.com/9360410/160949320-16580794-f5b2-4856-aa85-d5420c2a1bfa.png)

![Screenshot (133)](https://user-images.githubusercontent.com/9360410/160949349-22c01247-c3f8-4e7d-8038-4babc99329e0.png)

The Screenshot below shows the running VM named 'sad' even after reinstall of Multipass.

![Screenshot 2022-03-31 004143](https://user-images.githubusercontent.com/9360410/160949412-6a40bb38-1677-480e-9ec0-c02e41504c2c.png)

And this is how I broke the VM.

```yaml
#cloud-config
packages:
  - screenfetch
users:
  - name: goran
    gecos: Foo B. Bar
    primary_group: goran
    groups: users, admin
    ssh_import_id: None
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCkoDvr1jJ3Y+u7A3wumHfDEtqLzzsLHnqtv2I4dWOKGcArICW6CPtUrlpKTamZP9wfMqzu8ToAiyGtk74ZZLXKtyToGyre2yTDeSlHPDPw8ZwPLpbW6xwiQJKVreAFXLlNVh7V1/Q0d0pMpTf5gSMJ2YcbQzQ0/0tIc2WyZzTGEp5c7Es8ZZph0ZpeXpregHHgIIX/Vc+CP8GWJPtDp++yZfvK/LTG449P57+ukNw5qcJhNpzJU0YtCWPhYBSeGxQ4NX2vDl+yvZe/dtLqA+RSyo/CsbtUl4DqzXWuyuGTrsS1MfJIIYbOnXJzUeDIw/j8wmjxlM7oroWdZ9h2TVxUbB77qQBO93utV3eKttmUkloaWIqiecTDVKtgSQ26XUo0MX7J73GaJnx/w4hHSkfd3sN8+3RGV4HSUqEz6+vY/oirfE3WlyjJIDLjsgxhXafGmHFI1/4zFI7A6yDyx0HJk0rf4ug3TLrGDhl/4bBDZhqWZNMTjjZr1VK8FSmaf/0dXGE5cRAin2B+IR4MAxk/BtBFvMpjFSMGxn0z5VYEHARhMtrhsQ2DeTBrQY9UWCKRf2C/nu2Ptw/oqR9wRfqcJRk46+soc0Sf23W2xTITxEQhelWZDkMzGkb7G7t1NNdbSKbTdkQaVqcbEgIt2vM5o9JA/MSPxQ3hUOD0thFXFQ== goran@DESKTOP-O30D13U
    lock_passwd: false
    passwd: $6$7TmZDuNDJeDbP$UHbWjUw1AKpDgxTN/yd8YT6PrfIS6arj0jAuNUfk8Dq8PGvgj90vu2AEuDwhMD5thdVVqcguxOYzpJWetE4Wg.
disk_setup:
  /dev/sda:
    table_type: 'gpt'
    layout:
      - 60
      - [10, 82]
      - 10
      - 10
      - 20
    overwrite: Ture
fs_setup:
  - label: tik
    filesystem: 'ext3'
    device: 'ephemeral0'
    partition: 'auto'
```

11. Installing beta version 1.9.0 works, after win update, who knows maybe the update reset some things, did not try 1.8 after win update.
