### ISSUE TITLE
Jellyfin appliance

### ISSUE THREAD

**Issue by ethicnology** [canonical/multipass#2550]
**What are you trying to do?**
appliance:[jellyfin](https://jellyfin.org/)  
Jellyfin is a free software alternative to Plex

**What's your proposed solution?**
I've [created a cloud-init](https://github.com/ethicnology/nubo-init) based on the [jellyfin documentation](https://jellyfin.org/docs/general/administration/installing.html#ubuntu) for Ubuntu 20.04

```yaml
#cloud-config

package_update: true

package_upgrade: true

packages:
  - apt-transport-https

runcmd:
  - add-apt-repository universe
  - curl -fsSL https://repo.jellyfin.org/ubuntu/jellyfin_team.gpg.key | gpg --dearmor -o /etc/apt/trusted.gpg.d/debian-jellyfin.gpg
  - echo "deb [arch=$( dpkg --print-architecture )] https://repo.jellyfin.org/ubuntu $( lsb_release -c -s ) main" | sudo tee /etc/apt/sources.list.d/jellyfin.list
  - apt update -y
  - apt install jellyfin -y
```
