### ISSUE TITLE
[blueprints] Allow defining aliases

### ISSUE THREAD

**Issue by townsend2010** [canonical/multipass#2643]
Make it possible to define and automatically create client-side aliases in the Blueprint definition.  It will look similar to:

```yaml
aliases:
  docker: docker:docker
  docker-compose: docker:docker-compose
  docker-foo: docker-worker:foo

instances:
  docker:
    ...
  docker-worker:
    ...
```
