### ISSUE TITLE
`multipass list` output format inconsistency for json and yaml

### ISSUE THREAD

**Issue by sed-i** [canonical/multipass#2823]
**Describe the bug**
The yaml output of `multipass list` significantly differs from the json output.
- `list` top level section in json doesn't exist in yaml
- vm names in yaml are sections but in json are values

**To Reproduce**
Compare output of the following two commands:
- `multipass list --format json`
- `multipass list --format yaml`

**Expected behavior**
Piping to yq or jq to work with the same path, however paths and contents differ.
- `multipass list --format yaml | yq '.charm-dev-2cpu-7g[0].ipv4[0]'`
- `multipass list --format json | jq '.list[].ipv4[1]'`

**Logs**
```
$ multipass list --format json
```
```json
{
    "list": [
        {
            "ipv4": [
            ],
            "name": "bundle-test",
            "release": "22.04 LTS",
            "state": "Stopped"
        },
        {
            "ipv4": [
                "10.43.8.208",
                "10.1.55.0"
            ],
            "name": "charm-dev-2cpu-7g",
            "release": "22.04 LTS",
            "state": "Running"
        },
        {
            "ipv4": [
            ],
            "name": "load-test",
            "release": "22.04 LTS",
            "state": "Stopped"
        },
        {
            "ipv4": [
            ],
            "name": "primary",
            "release": "20.04 LTS",
            "state": "Stopped"
        }
    ]
}
```

```
$ multipass list --format yaml
```
```yaml
primary:
  - state: Stopped
    ipv4:
      []
    release: 20.04 LTS
bundle-test:
  - state: Stopped
    ipv4:
      []
    release: 22.04 LTS
charm-dev-2cpu-7g:
  - state: Running
    ipv4:
      - 10.43.8.208
      - 10.1.55.0
    release: 22.04 LTS
load-test:
  - state: Stopped
    ipv4:
      []
    release: 22.04 LTS
```

**Additional info**
- multipass   1.10.1
- multipassd  1.10.1

**Additional context**
NTA.
