### ISSUE TITLE
Custom image repository (`multipass config`)

### ISSUE THREAD

**Issue by Saviq** [canonical/multipass#307]
`multipass config` should edit an annotated yaml:

```
defaults:
  image: default        # see `multipass find` for available images or use file:// or http:// URLs
  cpus: 1               # recommended at most one below your host's cores
  disk: 5GB             # this is the maximum the instance can use, so go big
  memory: 2GB           # maximum the instance can use, shared between host and instances
  cloud-init: {}        # see http://cloudinit.readthedocs.io/en/latest/topics/examples.html
  mounts:
    /local/path: remote/path

# aliases:
#   example:            # this is the image name to use for `multipass launch`
#     aliases: [ex]     # an optional list of alternative names
#     image: default    # defaults to "example" or defaults.image above
#     cpus: 2
#   lts:                # this overrides the disk size when launching "lts"
#     disk: 10GB
```

The above is what I think the ultimate would be in terms of usability, we can do it in stages to simplify.

We should be able to inject a set of aliases in multipassd, for example:

```
aliases:
  core16:
    aliases: [core]
    image: http://cdimage.ubuntu.com/ubuntu-core/16/current/ubuntu-core-16-amd64.img.xz
  core18-build:  # TBD
    image: 18.04
```

Those should be recursively merged with the `aliases` key from `multipass config`, the latter taking precedence.

On `multipass launch` we first look up the entry in the `aliases` dictionary, if it doesn't have an `image` key, we see if it's a valid alias in our streams (we don't look back at the `aliases` dict) and if so, store it in the `image` key. Then apply `defaults` and we should have all the data to actually launch the instance.

Iterations:

- [x] support `core` (and prepare for `core18`) _internal_ aliases, no config necessary
- [ ] support overriding defaults:
  ```
  defaults:
    image: default        # see `multipass find` for available images or use file:// or http:// URLs
    cpus: 1               # recommended at most one below your host's cores
    disk: 5GB             # this is the maximum the instance can use, so go big
    memory: 2GB           # maximum the instance can use, shared between host and instances
    cloud-init: {}        # see http://cloudinit.readthedocs.io/en/latest/topics/examples.html
    mounts:
      /local/path: remote/path
  ```
- [ ] support custom aliases:
  ```
   aliases:
     example:            # this is the image name to use for `multipass launch`
       aliases: [ex]     # an optional list of alternative names
       image: default    # defaults to "example"
       cpus: 2
  ```
- [ ] support overriding defaults for _upstream_ aliases:
  ```
  aliases:
    lts:
      memory: 2GB
  ```

**Comment by townsend2010** [comment]
After working on this a bit, I propose the following for supporting custom aliases to fall more in line with how we handle SimpleStreams data:
```
image_repository:
  - 
    aliases:
      - core
      - core-16
      - core16
    image_info:
      image: http://cdimage.ubuntu.com/ubuntu-core/16/current/ubuntu-core-16-amd64.img.xz
      name: core-16                 # Analogous to 'release' in SimpleStreams
      friendly_name: 'Core 16'  # Analagous to 'release_title' in SimpleStreams
      image_hash:                    # Real hash or hash file location
  -
    aliases:
      - core-18
      - core18
    image_info:
      image: file://some/path/to/ubuntu-core-18-amd64.img.xz
      name: core-18
      friendly_name: 'Core 18'
```
This way, it is a just list of aliases & info and that we can more easily iterate over the full list of aliases for a given entry in the list.

- If`name` is missing, it will use the first alias given in the `aliases` list.
- `friendly_name` would be used for `list` and `info` output, so if it's missing, it'll just use `Not Available` in the output.
- If info for `image_hash` is missing, it'll just compute the sha256 for the image being pointed to and use that for the `id` in the vault.

**Comment by townsend2010** [comment]
For the next part where the instance is configured, I think that should be a separate section apart from the `image_repository`.  This is how I envision it looking:
```
instance_config:
  default:
    image: default        # see `multipass find` for available images or use file:// or http:// URLs
    cpus: 1               # recommended at most one below your host's cores
    disk: 5GB             # this is the maximum the instance can use, so go big
    memory: 2GB           # maximum the instance can use, shared between host and instances
    cloud-init: {}        # see http://cloudinit.readthedocs.io/en/latest/topics/examples.html
    mounts:
    - /local/path: remote/path
  overrides:
  - aliases:
    - core16
    - core-16
    config:
      cpus: 2
  - aliases:
    - core
    config:
      memory: 4GB
```
This way, a user can have multiple aliases defined for a particular image, but each alias can have its own separate instance configuration.  For example, in `image_repository` example in the preceding comment, the user can have `core`, `core16`, and `core-16` and aliased for the same image, but the `instance_config` can be different for each alias if they so choose.

**Comment by Saviq** [comment]
I feel like we shouldn't drive the UX with how our internal data structures work...
- `image_info` key feels redundant?
- What would `name` be used for? Can't we just use whatever the user asked for when launching? Or the first alias?
- `friendly_name` sure, if optional, but fall back to ↑
- `image_hash` - is that for verifying the image? Maybe, but we should definitely try and be smart about it - detect `.md5sum` files in the destination if this is not provided. If we also use it for our ID, fine, but that shouldn't be its primary use case.

As for `overrides` I feel this is over-engineered. The 80-20 rule suggest this whole "composition" of overrides (what if they conflict?) would rarely be used but would require significant effort from our side.

> This way, a user can have multiple aliases defined for a particular image, but each alias can have its own separate instance configuration.

The same can be achieved with little repetition in my original proposal, only with some repetition?

Overall, I think we should aim for simplicity here rather than exhausting all the options. Optimize for a simple case of mapping `alias` to `image_url`.

I think we should even accept the following:

```
aliases:
  my-alias: https://image/url
```

So if the value of an entry in the `aliases` (I'm not insisting on this name, FWIW) is a string, we "expand" it to:
```
aliases:
  my-alias:
    image: https://image/url
```

**Comment by townsend2010** [comment]
What I'm trying to accomplish here is to mimic as best we can what we do for handling SimpleStreams manifests and creating an entry in the image vault (not instance 'vault').  We made quite a few assumptions in that we derive much of the definition of our image vault from information obtained from SimpleStreams.  I would really like to avoid re-engineering the image vault handling to fit a custom repository that contains very minimal information and would rather try to make the custom repository have enough information to create a SimpleStreams manifest from it.

I assume we will want to store prepared source images in the image vault because otherwise, any time a user wants to create an instance based on this image alias, it will need to be downloaded (if http based) and then prepared every time.

> `image_info`  key feels redundant?

I wanted to put all image information under a single collection to keep it separate from aliases that are associated with it.  Of course it's not really necessary, but I thought it made it look better organized.

> What would `name` be used for? Can't we just use whatever the user asked for when launching? Or the first alias?

We use this value for creating the directory the image is stored in in the image vault.  As I mentioned, if it is left out, we can just use the first alias given.

> `friendly_name` sure, if optional, but fall back to ↑

As I mentioned in my proposal, this is what is displayed in the `list` and `info` commands, so I wonder if just putting the alias there is going to look strange.  For example, the `list` command would look something like this if someone created an alias called `my-alias` and then used that for an instance called `my-instance`:
```
Name                    State       IPv4             Release
my-instance             STOPPED     --               my-alias
```
This is why I proposed if `friendly_name` is missing, we display `Not Available` there.

> `image_hash` - is that for verifying the image? 

That is one reason for it.

> Maybe, but we should definitely try and be smart about it - detect `.md5sum` files in the destination if this is not provided.

We can definitely make trying to find `.md5sum` files a goal, but I have found that many times, they are located somewhere else, like for Fedora cloud images.  Also, if a user points to a local file on the machine, we can't do much about that:)

>  If we also use it for our ID, fine, but that shouldn't be its primary use case.

We absolutely use it for the unique ID in the image vault.  This is why I proposed just computing the sha256 either from the URL given or from the image itself if `image_hash` is not given because we definitely need *something* for an ID.

Regarding `overrides`, ok, that may be a bit too much, but I do feel that in a given block of aliases and it's image definition, we should have a separate collection of how an instance would be defined.  For example:
```
default_instance_config:
    image: default        # see `multipass find` for available images or use file:// or http:// URLs
    cpus: 1               # recommended at most one below your host's cores
    disk: 5GB             # this is the maximum the instance can use, so go big
    memory: 2GB           # maximum the instance can use, shared between host and instances
    cloud-init: {}        # see http://cloudinit.readthedocs.io/en/latest/topics/examples.html
    mounts:
    - /local/path: remote/path

image_repository:
  - aliases:
    - core
    - core-16
    - core16
    image_info:
      image: http://cdimage.ubuntu.com/ubuntu-core/16/current/ubuntu-core-16-amd64.img.xz
      name: core-16                 # Analogous to 'release' in SimpleStreams
      friendly_name: 'Core 16'      # Analagous to 'release_title' in SimpleStreams
      image_hash:                   # Real hash or hash file location
    instance_config:
      memory: 4GB
```

**Comment by Saviq** [comment]
Sure, but what we shouldn't be doing is pushing those assumptions down onto the users :)

If the keys don't clash, why group them? Only to have the user copy/paste/type the `image_info:` `instance_config:` keys every time?

If we apply this to our "minimal case":

```
image_repository:
- aliases:
  - my-alias
  image_info:
    image: https://image/url
```

I just want more substance than overhead. Compare that to:

```
image_repository:
  my-alias: https://image/url
```
Or even the expanded case:
```
image_repository:
  my-alias:
    image: https://image/url
```

As for "inheritance", in YAML you can do:

```
image_repository:
  big-lts: &big
    image: lts
    cpus: 4
    memory: 8GB
    disk: 50GB
  big-devel:
    <<: *big
    image: devel
```

This takes the values from `big-lts` and applies it to `big-devel`, which overrides the `image` key as well.

**Comment by townsend2010** [comment]
I view yaml as a human friendly schema, and as such, I think we like to see things in groups of common items.  I feel like just populating a list entry with somewhat non-related keys all at the same level seems a little unfriendly.  I see image information as being one group and instance configuration information being another group.  If we document the yaml well, then I don't see why users would balk at that having an extra key to define a collection.

Also, I'd really like all aliases in an entry to be in it's own list to make iterating over all aliases in an entry simpler.  If we want to do it your way, then I say we limit each entry to one alias.

Sure `image_repository` doesn't make sense once we start adding instance definition keys into the fray.  It's more like `alias_definitions` or `launch_config` or something.

> And what's wrong with `defaults`?

I envision this yaml configuration file to be multipassd's global configuration file for other configuration parameters, so I think `default` is a little too general being a top level key name.

**Comment by Saviq** [comment]
> populating a list entry with somewhat non-related keys all at the same level seems a little unfriendly.

IMO they are all related - to the instance you want to launch out of it. You know an "image" is an entity in our repository, so you group those in your mind. But I bet you that a huge proportion of all the entries in this map will not have any of the image properties other than the path. And that unnecessary indirection in this case is what I frown upon.

So maybe we can expand only if needed?
```yaml
image_repository:
  my-alias: my-image
```
would expand to:
```yaml
image_repository:
  my-alias:
    image: my-image
```
would expand to:
```yaml
image_repository:
  my-alias:
    image:
      path: my-image
```
So the user would decide how deep they want to go?

> Also, I'd really like all aliases in an entry to be in it's own list to make iterating over all aliases in an entry simpler. If we want to do it your way, then I say we limit each entry to one alias.

I think we need to support multiple aliases so that ultimately you can apply a group of props to a set of aliases, but again most use cases will just have one alias, so introducing a mandatory `aliases` key feels wasteful. Unfortunately in YAML you can't have lists as keys of a dictionary, so

```yaml
image_repository:
  [my-alias, your-alias]: http://image/path
```
is not possible. But again, I don't think we should push on users something that "makes iterating simpler". You only have to read this YAML, not have it be your data structure.

@albaguirre @gerboland what do you guys think?

> I envision this yaml configuration file to be multipassd's global configuration file for other configuration parameters, so I think default is a little too general being a top level key name.
Maybe `launch_defaults`?

**Comment by townsend2010** [comment]
> So maybe we can expand only if needed?
So the user would decide how deep they want to go?

I'm not sure I really understand what you mean here.  When implementing this, we need to know what the schema is ahead of time and what keys are supported, so unless I misunderstand what you are saying, we need to agree on how the keys are going to be laid out and not leave it up to user how deep they want to go.

Also, I'll concede in making aliases a list and instead, use the first alias as the key and have an option for a list of alternate aliases.

And as for top-level keys, I'm good with calling the default launch configuration `launch_defaults` and also instead of calling it `image_repository`, let's call it `launch_config`...or maybe `launch_overrides`?

**Comment by townsend2010** [comment]
Another question about this...do we want `multipass find` to query any user configured aliases?

**Comment by gerboland** [comment]
I prefer @Saviq 's initial proposal. The term "alias" to me implies that there's already another name. I think is is straight-forward for the common use-case: adding a single custom image.

    image_repository:
        image_name:
            image: <path/url>

Any more minimal, it'll be too limiting, and then the "expanding" idea kicks in, which is tough to parse and not worth the trouble for such a small benefit IMO. Let's avoid this "expanding" magic.

I like the "defaults" section at the top. I like that every key in the defaults section also applies to each custom image definition, so each can be overridden. That should make parsing easier.

**Comment by gerboland** [comment]
And yes, "multipass find" should show user-configured aliases. I'm thinking of server/client situations where an admin configures MP server with additional images, we need a way for the user to find them.

**Comment by Saviq** [comment]
> I'm not sure I really understand what you mean here. When implementing this, we need to know what the schema is ahead of time and what keys are supported, so unless I misunderstand what you are saying, we need to agree on how the keys are going to be laid out and not leave it up to user how deep they want to go.

What I mean is that for a given key, we can support both a "simple" schema (a string) as well as a complex one (a map). So the three snippets I posted before would be equivalent and accepted.

@gerboland As for it being complex to parse... Not something we should be optimizing for.
```python
if type(value) == str:
  # assign value
else:
  # parse deeper
```

I'd say it can be generalized quite a bit... And IMO yes, worth it - for a case we should optimize for:
```yaml
image_repository:
    image1:
        image: <path/url>
    image2:
        image: <path/url>
    image3:
        image: <path/url>
    image4:
        image: <path/url>
    image5:
        image: <path/url>
```
vs.
```yaml
image_repository:
    image1: <path/url>
    image2: <path/url>
    image3: <path/url>
    image4: <path/url>
    image5: <path/url>
```

And yes, they have to exist in `find`.
