### ISSUE TITLE
Add strict snap confinement

### ISSUE THREAD

**Issue by Saviq** [canonical/multipass#310]
```
multipassd:
  plugs:
  - kvm
  - multipass-support
  - network

multipass:
  plugs:
  - home
  - ssh (?)
```
