### ISSUE TITLE
Add merge how

### ISSUE THREAD

**Issue by mneverov** [canonical/multipass#3165]
Currently, when a template with cloud init is used the latter overrides commands in the template.
For example `multipass launch docker --name dckr --cloud-init cloud-config.yaml` where cloud-config.yaml is defined as:
```yaml
#cloud-config
# vim: syntax=yaml

packages:
  - acl
```

```sh
multipass shell dckr
systemctl status docker
# no docker installed
```

In order for [cloud config merge](https://cloudinit.readthedocs.io/en/19.3/topics/merging.html) works the header should be specified in both configs.
Please add `merge_how` to the blueprints.

```yaml
merge_how:
 - name: list
   settings: [append]
 - name: dict
   settings: [no_replace, recurse_list]
```
