### ISSUE TITLE
Error loading cloud-init config: bad file - multipass and cloud-init

### ISSUE THREAD

**Issue by tersucorp** [canonical/multipass#3693]
**Describe the bug**
I get the error below when trying to create vms with multipass and cloud init.
```
error loading cloud-init config: bad file
error loading cloud-init config: bad file
error loading cloud-init config: bad file
error loading cloud-init config: bad file
```

**To Reproduce**
1. install multipass `1.14.0`
2. install cloud init `24.2-0ubuntu1~24.04.2`
3. create a cloud-init config file in config/debian-cloud-init.yaml:
```
#cloud-config
package_update: true
packages:
  - debootstrap
users:
  - name: root
    lock_passwd: false
    passwd: tersu
ssh_pwauth: true
disable_root: false
runcmd:
  - debootstrap --arch=arm64 bookworm /mnt http://deb.debian.org/debian/
  - mount --bind /dev /mnt/dev
  - mount --bind /proc /mnt/proc
  - mount --bind /sys /mnt/sys
  - |
      chroot /mnt /bin/bash -c "apt-get update && \
      apt-get install -y linux-image-arm64 systemd-sysv"
  - chroot /mnt /bin/bash -c "apt-get install -y grub-efi"
  - |
      chroot /mnt /bin/bash -c "grub-install --target=arm64-efi \
      --efi-directory=/boot/efi --bootloader-debian --recheck"
  - chroot /mnt /bin/bash -c "update-grub"
  - |
      chroot /mnt /bin/bash -c "echo 'deb http://deb.debian.org/debian/ \
      bookworm main' > /etc/apt/sources.list"
  - chroot /mnt /bin/bash -c "echo 'root:password' | chpasswd"
  - |
      chroot /mnt /bin/bash -c "sed -i 's/^#PermitRootLogin.*/\
      PermitRootLogin yes/' /etc/ssh/sshd_config"
  - chroot /mnt /bin/bash -c "systemctl enable ssh"
  - umount /mnt/dev
  - umount /mnt/proc
  - umount /mnt/sys
  - echo "Debian installation completed!"
```

4. Create a bash script to create vms using multipass and cloud-init
```
#!/bin/bash

# Launch VMs with multipass
multipass launch --name jumpbox --cpus 1 --memory 512M --disk 5G --cloud-init ./config/debian-cloud-init.yaml --verbose
multipass launch --name master --cpus 1 --memory 2G --disk 10G --cloud-init ./config/debian-cloud-init.yaml --verbose
multipass launch --name worker1 --cpus 1 --memory 2G --disk 10G --cloud-init ./config/debian-cloud-init.yaml --verbose
multipass launch --name workder2 --cpus 1 --memory 2G --disk 10G --cloud-init ./config/debian-cloud-init.yaml --verbose
```

5. Run the bash script

**Expected behavior**
It should create the multipass VMs with the specified config

**Logs**
[multipass log file.log](https://github.com/user-attachments/files/17115735/multipass.log.file.log)

**Additional info**
 - OS: OS: Ubuntu 24.04.1 LTS x86_64
 - multipass version `1.14.0`
- cloud init version `24.2-0ubuntu1~24.04.2`
- `multipass get local.driver`: qemu

**Additional context**

config is valid
```
cloud-init schema -c config/debian-cloud-init.yaml                                                                                13:31:44
Valid schema config/debian-cloud-init.yaml
```
