### ISSUE TITLE
Daemon crashed and could not recover unknown instance

### ISSUE THREAD

**Issue by DreamerLWJ** [canonical/multipass#4002]
**Describe the bug**
Daemon crashed and could not recover unknown instance

**To Reproduce**

How, and what happened?

1. When I applied the netplan file, the instance crashed. I set the static IP address as usual. The edited netplan file is as follows.
```yaml
network:
  version: 2
  ethernets:
    default:
      match:
        macaddress: "52:54:00:e7:46:6b"
      dhcp4: no
      addresses:
        - 192.168.68.20/24
      routes:
        - to: 0.0.0.0/0
          via: 192.168.68.1
    extra0:
      match:
        macaddress: "52:54:00:8d:f9:c3" 
      optional: true
      dhcp-identifier: "mac"
      dhcp4: true
      dhcp4-overrides:
        route-metric: 200
```

```shell
$ sudo netplan try
```

2. And then, it crashed. The GUI always displays "Waiting for daemon".

Then no matter I reinstall v1.15.1 and v1.14.1 through brew or pkg, the following operations always crash.

3. When I tried to stop an instance in an unknown state, the daemon crashed again and again.

```shell
$ multipass list
Name                    State             IPv4             Image
apollo                  Unknown           --               Ubuntu 24.04 LTS
hera                    Running           192.168.68.27    Ubuntu 24.04 LTS
                                          192.168.2.102
zeus                    Running           192.168.68.25    Ubuntu 24.04 LTS
                                          192.168.2.100
$ multipass stop apollo
```

**Expected behavior**
What did you expect to happen?

- When I execute the `netplan` command it shouldn't crash.
- When I try to force stop the instance, it shouldn't crash, otherwise the unknown instance cannot be recovered.

**Logs**
Please provide logs from the daemon, see [[accessing logs](https://canonical.com/multipass/docs/accessing-logs)](https://canonical.com/multipass/docs/accessing-logs) on where to find them on your platform.

[multipassd.log](https://github.com/user-attachments/files/19433179/multipassd.log)

[multipass_gui.log](https://github.com/user-attachments/files/19433182/multipass_gui.log)

**Additional info**

- OS: macOS 15.3.2
- CPU architecture or model: Apple M1
- `multipass version`

```shell
multipass   1.15.1+mac
multipassd  1.15.1+mac
```

- `multipass info`

```shell
Name:           apollo
State:          Unknown
Snapshots:      0
IPv4:           --
Release:        --
Image hash:     103f31c5a5b7 (Ubuntu 24.04 LTS)
CPU(s):         --
Load:           --
Disk usage:     --
Memory usage:   --
Mounts:         --

Name:           hera
State:          Running
Snapshots:      0
IPv4:           192.168.68.27
                192.168.2.102
Release:        Ubuntu 24.04.2 LTS
Image hash:     103f31c5a5b7 (Ubuntu 24.04 LTS)
CPU(s):         1
Load:           0.03 0.01 0.00
Disk usage:     2.0GiB out of 4.8GiB
Memory usage:   219.0MiB out of 952.9MiB
Mounts:         --

Name:           zeus
State:          Running
Snapshots:      0
IPv4:           192.168.68.25
                192.168.2.100
Release:        Ubuntu 24.04.2 LTS
Image hash:     103f31c5a5b7 (Ubuntu 24.04 LTS)
CPU(s):         1
Load:           0.00 0.00 0.00
Disk usage:     1.9GiB out of 4.8GiB
Memory usage:   214.4MiB out of 952.9MiB
Mounts:         --
```

- `multipass get local.driver`

```shell
qemu
```

**Additional context**

**Comment by DreamerLWJ** [comment]
I can indeed reproduce this issue 100%, and it's related to netplan.

**Comment by DreamerLWJ** [comment]
When an issue occurs, the daemon's `list` operation will prompt failure. After I delete the problematic instance, the daemon will immediately recover as if nothing had happened.

**Comment by xmkg** [comment]
Hi @DreamerLWJ, sorry you're experiencing this issue. I've tried the steps and reproduced the issue.

The problem here is that Multipass is losing connectivity to the VM after the netplan changes, due to the changes happening in the primary interface. The daemon constantly tries to re-establish the connection using the old IP address, but unable to reach it since it no longer uses that IP address:

```
/*...*/
[2025-03-24T23:48:40.369] [debug] [apollo] Caching new SSH session
[2025-03-24T23:48:42.378] [info] [apollo] SSH session disconnected
[2025-03-24T23:48:42.378] [debug] [apollo] Caching new SSH session
[2025-03-24T23:48:44.384] [info] [apollo] SSH session disconnected
[2025-03-24T23:48:44.385] [debug] [apollo] Caching new SSH session
/*...*/
```

> After I delete the problematic instance, the daemon will immediately recover as if nothing had happened.

When the instance is deleted, the daemon finally gives up the attempts and finally can attend to the other business it has to run. During my attempts, I noticed that Netplan does not seem to revert the problematic configuration after the timeout (or maybe it reverts, but Multipass does not pick it). I'll look into that separately.

The default interface in Multipass doubles as a management interface, so the new netplan configuration should not interfere with it. My suggestion is to keep the default interface as-is and add your extra static interface on top of it (i.e. do not modify the "default"). I tried this way, and it works. Also, make sure that the MAC addresses for the default and the extra are indeed the "default" and "extra" MAC addresses.

Could you try the suggestion above and let me know if it works?

Thanks!

**Comment by DreamerLWJ** [comment]
@xmkg Thank you for your reply! It seems that the issue is indeed due to multipass not being able to connect to the instance. Following your advice, the problem has been avoided.

Additionally, I can make it work by setting the static IP of the default interface to the initial DHCP assigned IP address. 
```shell
$ ip addr show
2: enp0s1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 52:54:00:68:b2:9b brd ff:ff:ff:ff:ff:ff
    inet 192.168.68.32/24 brd 192.168.68.255 scope global enp0s1
       valid_lft forever preferred_lft forever
    inet6 fddb:6cc0:745f:c41c:5054:ff:fe68:b29b/64 scope global dynamic mngtmpaddr noprefixroute 
       valid_lft 2591991sec preferred_lft 604791sec
    inet6 fe80::5054:ff:fe68:b29b/64 scope link 
       valid_lft forever preferred_lft forever
```
```yaml
network:
  version: 2
  ethernets:
    default:
      match:
        macaddress: "52:54:00:68:b2:9b"
      dhcp4: no
      addresses:
        - 192.168.68.32/24
      routes:
        - to: 0.0.0.0/0
          via: 192.168.68.1
    extra0:
      match:
        macaddress: "52:54:00:5a:cc:a4"
      optional: true
      dhcp-identifier: "mac"
      dhcp4: true
      dhcp4-overrides:
        route-metric: 200
```
```shell
$ sudo netplan apply
# Everything is working correctly.
```
I'm not sure if there will be long-term problems from doing this, in any case, I am very grateful for your answer!
