### ISSUE TITLE
UID/GID mapping missing in `info` output

### ISSUE THREAD

**Issue by Saviq** [canonical/multipass#439]
```json
$ cat /var/snap/multipass/common/data/multipassd/multipassd-vm-instances.json
[...]
        "mounts": [
            {
                "gid_mappings": [
                    {
                        "host_gid": 1000,
                        "instance_gid": 1001
                    }
                ],
                "source_path": "/home/michal/dev/canonical/snappy/edledit",
                "target_path": "/home/multipass/project",
                "uid_mappings": [
                    {
                        "host_uid": 1000,
                        "instance_uid": 1001
                    }
                ]
            }
        ],
```

But:
```yaml
# $ multipass info --format=yaml snapcraft-edledit                             
# […]
    mounts:
      /home/multipass/project:
        - gid_mappings:
            - ~
          uid_mappings:
            - ~
          source_path: /home/michal/dev/canonical/snappy/edledit
```
